kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: openshift-distributed-tracing
resources:
    - namespace.yaml
components:
    - ../../../../components/limitranges/default
    - ../../../../components/project-admin-rolebindings/operate-first
