---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:
  - clusterlogging.yaml
  - rolebindings
  - roles
  - ../../cluster-scope/base/operators.coreos.com/operatorgroups/cluster-logging
