apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: odhservicemonitor
spec:
  endpoints:
    - port: web             # Prometheus
    - port: metrics         # Argo
    - port: grafana         # grafana
    - port: http-metrics    # grafana-operator, Open Data Hub operator
    - port: 8080-tcp        # Jupyterhub
      path: "/metrics"
  selector: {}
  namespaceSelector:
    matchNames:
      - opf-jupyterhub
      - opf-argo
      - opf-monitoring
      - openshift-operators
