apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acm.yaml
  - alertreceiver.yaml
  - argocd-notifications.yaml
  - argocd-projects.yaml
  - argocd.yaml
  - cert-manager.yaml
  - cluster-resources.yaml
  - keycloak.yaml
  - kubevirt-hyperconverged.yaml
  - moc-nfs-democratic-csi.yaml
