apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acm.yaml
  - alertreceiver.yaml
  - argocd-notifications.yaml
  - argocd-projects.yaml
  - argocd.yaml
  - cert-manager.yaml
  - cluster-resources.yaml
  - external-secrets.yaml
  - kubevirt-hyperconverged.yaml
  - odf-fake-metrics-exporter.yaml
