---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/superset

patchesJson6902:
  - patch: |
      - op: add
        path: /spec/applications/-
        value:
          kustomizeConfig:
            repoRef:
              name: opf
              path: overlays/moc/superset/overrides
          name: superset
      - op: add
        path: /spec/repositories
        value:
          name: opf
          uri: https://github.com/operate-first/odh/tarball/master
    target:
      group: kfdef.apps.kubeflow.org
      kind: KfDef
      name: opendatahub
      version: v1
