---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/clusterrolebindings/self-provisioners
  - ../../../base/configs/project
  - ../../../base/groups/ai-services
  - ../../../base/groups/argocd-admins
  - ../../../base/groups/b4mad
  - ../../../base/groups/cnv-testing
  - ../../../base/groups/data-science
  - ../../../base/groups/fde
  - ../../../base/groups/lab-cicd
  - ../../../base/groups/mesh-for-data
  - ../../../base/groups/open-aiops
  - ../../../base/groups/operate-first
  - ../../../base/groups/ray
  - ../../../base/groups/rekor
  - ../../../base/groups/sa-dach
  - ../../../base/groups/sdap-mslsp
  - ../../../base/groups/thoth
  - ../../../base/groups/tufts-dcc-6
  - ../../../base/groups/uky-redhat
  - ../../../base/groups/workshops
  - alertmanager-main-secret.yaml

generators:
  - secret-generator.yaml
