---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-datacatalog

resources:
  - ../../../base/datacatalog
  - bucket.yaml

patchesJson6902:
  - path: kfdef_patch.yaml
    target:
      group: kfdef.apps.kubeflow.org
      kind: KfDef
      name: opendatahub
      version: v1
