---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opf-superset

resources:
  - namespace.yaml

components:
  - ../../../components/project-admin-rolebindings/operate-first
  - ../../../components/monitoring-rbac
  - ../../../components/odh-dashboard
  - ../../../components/limitranges/default
  - ../../../components/resourcequotas/x-small
