apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertreceiver.yaml
  - cluster-resources.yaml
  - external-secrets.yaml
  - local-storage.yaml
  - kubevirt-hyperconverged.yaml
  - nfd.yaml
