apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/apicurio
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/x-small
kind: Kustomization
namespace: apicurio-apicurio-registry
resources:
- namespace.yaml
