apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generators:
  - secret-generator.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-notifications-cm
    patch: |
      - op: add
        path: /data/context/argocdUrl
        value: https://argocd-server-argocd.apps.moc-infra.massopen.cloud/
