apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - cloudbeaver.yaml
  - cluster-resources.yaml
  - das.yaml
  - dex.yaml
  - dex-secondary.yaml
  - external-secrets.yaml
  - kepler.yaml
  - grafana.yaml
  - k8s-annotations-exporter.yaml
  - kfdefs.yaml
  - odh-operator.yaml
  - training-operator.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/project
        value: os-climate
    target:
      group: argoproj.io
      kind: Application
