apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/project-admin-rolebindings/data-science
- ../../../../components/limitranges/default
kind: Kustomization
namespace: ds-ml-workflows-ws
resources:
- namespace.yaml
- resourcequota.yaml
