---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opf-ci-test-pods

resources:
- namespace.yaml

components:
  - ../../../components/project-admin-rolebindings/thoth-devops
  - ../../../components/project-admin-rolebindings/operate-first
  - ../../../components/limitranges/default
  - ../../../components/resourcequotas/small
