---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thoth-amun-inspection-prod

resources:
  - namespace.yaml

components:
  - ../../../components/project-admin-rolebindings/thoth-devops
  - ../../../components/monitoring-rbac
