apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub-operator

# Source: https://github.com/opendatahub-io/opendatahub-operator/tree/master/kustomize/overlays/opendatahub
resources:
- deployment.yaml
- serviceaccount.yaml

images:
- name: quay.io/opendatahub/opendatahub-operator
  newTag: v1.0.8
