apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apicurio-registry.yaml
  - b4mad.yaml
  - cluster-management.yaml
  - data-science.yaml
  - fybrik.yaml
  - global_project.yaml
  - lab-cicd.yaml
  - mocops.yaml
  - octo-ushift-dev.yaml
  - okd-team.yaml
  - operate-first.yaml
  - os-climate.yaml
  - rekor.yaml
  - thoth.yaml
  - tremor-demo.yaml
  - workshops.yaml
  - chris.yaml
  - otel-dev.yaml
  - copilot-ops.yaml
  - kepler.yaml
