apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.ray.io
- ../../base/apiextensions.k8s.io/customresourcedefinitions/rayjobs.ray.io
- ../../base/apiextensions.k8s.io/customresourcedefinitions/rayservices.ray.io
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/kuberay-operator
- ../../base/rbac.authorization.k8s.io/clusterroles/kuberay-operator
