---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-observatorium

resources:
  - ../../../base/instance
  - ./grafana-data-sources
  - ./objectbucketclaims

generators:
  - secrets/secret-generator.yaml
