---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: store
  app.kubernetes.io/version: main-2021-11-11-aee7c97b
resources:
  - shard-0
  - shard-1
