---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-monitoring
components:
  - ../../../components/rbac
resources:
  - ../../../base/monitoring
  - ./servicemonitors
  - dashboards
  - datasource
