---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: odh-monitoring
  labels:
    app: prometheus
    prometheus: k8s
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: opf-monitoring
        port: web
  externalUrl: "http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/"
  podMonitorSelector: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
  securityContext: {}
  ruleSelector:
    matchLabels:
      prometheus: odh-monitoring
      role: alert-rules
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  remoteWrite:
    - url: "http://opf-observatorium-thanos-receive.opf-observatorium.svc.cluster.local:19291/api/v1/receive"
  replicas: 2
  retention: 7d
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
