---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: odh-monitoring
  labels:
    app: prometheus
    prometheus: k8s
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: opf-monitoring
        port: web
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
  securityContext: {}
  ruleSelector:
    matchLabels:
      prometheus: odh-monitoring
      role: alert-rules
  replicas: 2
  retention: 7d
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
