---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-observatorium
commonLabels:
  app.kubernetes.io/instance: observatorium
  app.kubernetes.io/part-of: observatorium
  app.kubernetes.io/name: loki
resources:
  - ../../../../base/instance/loki
  - servicemonitors

patchesStrategicMerge:
  - configmaps/observatorium-loki-configmap_patch.yaml

generators:
  - secrets/secrets-generator.yaml
