---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/clusterrolebindings/cluster-admins-rb
  - ../../../base/groups/cluster-admins
  - ../../../base/hostpathprovisioners/hostpath-provisioner
  - ../../../base/ingresscontrollers/default
  - ../../../base/machineconfigs/hostpath-provisioner-selinux
  - ../../../base/namespaces/hostpath-provisioner
  - ../../../base/namespaces/openshift-cnv
  - ../../../base/namespaces/openshift-storage
  - ../../../base/oauths/cluster
  - ../../../base/operatorgroups/openshift-storage
  - ../../../base/subscriptions/kubevirt-hyperconverged
  - ../../../base/storageclasses/hostpath-provisioner
  - ../../../base/subscriptions/ocs-operator
  - ../../../base/subscriptions/web-terminal

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
  - subscriptions/kubevirt-hyperconverged_patch.yaml
  - subscriptions/ocs-operator_patch.yaml
  - subscriptions/web-terminal.yaml
