apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../common
    - ../../../../base/apiextensions.k8s.io/customresourcedefinitions/workflow.argoproj.io
    - ../../../../base/apiextensions.k8s.io/customresourcedefinitions/workflowtemplate.argoproj.io
    - ../../../../base/config.openshift.io/oauths/cluster
    - ../../../../base/core/configmaps/cluster-monitoring-config
    - ../../../../base/core/namespaces/acme-operator
    - ../../../../base/core/namespaces/opf-kafka
    - ../../../../base/core/namespaces/thoth-amun-api-prod
    - ../../../../base/core/namespaces/thoth-amun-inspection-prod
    - ../../../../base/core/namespaces/thoth-backend-prod
    - ../../../../base/core/namespaces/thoth-frontend-prod
    - ../../../../base/core/namespaces/thoth-graph-prod
    - ../../../../base/core/namespaces/thoth-infra-prod
    - ../../../../base/core/namespaces/thoth-middletier-prod
    - ../../../../base/operators.coreos.com/operatorgroups/opf-kafka
    - ../../../../base/operators.coreos.com/subscriptions/cert-manager
    - ../../../../base/operators.coreos.com/subscriptions/strimzi
    - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
    - ../../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
    - ../../../../base/user.openshift.io/groups/cluster-admins
generators:
    - secret-generator.yaml

patchesStrategicMerge:
    - configmaps/cluster-monitoring-config.yaml
    - oauths/cluster_patch.yaml
    - groups/cluster-admins.yaml
