---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - ../../../../base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev
  - ../../../../base/apiextensions.k8s.io/customresourcedefinitions/prowjobs.prow.k8s.io
  - ../../../../base/config.openshift.io/oauths/cluster
  - ../../../../base/core/namespaces/acme-operator
  - ../../../../base/core/namespaces/dex
  - ../../../../base/core/namespaces/openshift-nmstate
  - ../../../../base/core/namespaces/openshift-pipelines
  - ../../../../base/core/namespaces/opf-ci-pipelines
  - ../../../../base/core/namespaces/opf-ci-prow
  - ../../../../base/core/namespaces/opf-ci-test-pods
  - ../../../../base/core/namespaces/tekton-pipelines
  - ../../../../base/core/namespaces/thoth-amun-api-prod
  - ../../../../base/core/namespaces/thoth-amun-inspection-prod
  - ../../../../base/core/namespaces/thoth-backend-prod
  - ../../../../base/core/namespaces/thoth-bots-prod
  - ../../../../base/core/namespaces/thoth-deployment-examples
  - ../../../../base/core/namespaces/thoth-frontend-prod
  - ../../../../base/core/namespaces/thoth-graph-prod
  - ../../../../base/core/namespaces/thoth-infra-prod
  - ../../../../base/core/namespaces/thoth-middletier-prod
  - ../../../../base/core/namespaces/opf-slack-first
  - ../../../../base/nmstate.io/nmstates/nmstate
  - ../../../../base/operators.coreos.com/operatorgroups/openshift-nmstate
  - ../../../../base/operators.coreos.com/subscriptions/cert-manager
  - ../../../../base/operators.coreos.com/subscriptions/kubernetes-nmstate-operator
  - ../../../../base/operators.coreos.com/subscriptions/openshift-pipelines-operator-rh
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-interceptor-opf-ci-pipelines
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard
  - ../../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
  - ../../../../base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard
  - ../../../../base/user.openshift.io/groups/cluster-admins
  - ingresscontrollers/default.yaml
  - machineconfigs/99-vlan-210-nfs.yaml
  - configmaps/cluster-monitoring-config.yaml

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
  - subscriptions/kubernetes-nmstate-operator_patch.yaml
  - subscriptions/openshift-pipelines-operator-rh_patch.yaml
