apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/seraph-host-inventory
  - ../../base/core/namespaces/seraph-ingress
  - ../../base/core/namespaces/seraph-platform-mq
