---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odh-operator

resources:
  - namespace.yaml

components:
  - ../../../components/project-admin-rolebindings/operate-first
  - ../../../components/monitoring-rbac
