apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aiops-tools-workshop
- api-designer
- apicurio-apicurio-registry
- copilot-ops
- dex
- janus-idp
- kubeflow
- openshift-config
- openshift-ingress
- openshift-logging
- openshift-monitoring
- openshift-storage
- opf-ci-prow
- opf-alertreceiver
- opf-grafana-public
- opf-jupyterhub
- opf-monitoring
- opf-observatorium
- opf-slack-first
- opf-superset
- opf-triage-party
- opf-trino
- opf-trino-stage
- service-catalog
- service-catalog-k8s-plugin
- okd-team
- okd-centos
- robozome
