apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertreceiver.yaml
  - cert-manager.yaml
  - cluster-resources.yaml
  - dex.yaml
  - external-secrets.yaml
  - kfdefs.yaml
  - moc-nfs-democratic-csi.yaml
  - node-labeler.yaml
  - odh-operator.yaml
  - nfd.yaml
  - kubevirt-hyperconverged.yaml
  - volsync.yaml
  - kepler.yaml
