apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertreceiver.yaml
  - cert-manager.yaml
  - cloudbeaver.yaml
  - cluster-resources.yaml
  - dex.yaml
  - kfdefs.yaml
  - moc-nfs-democratic-csi.yaml
  - node-labeler.yaml
