---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odh-trino
resources:
  - kfdef.yaml
  - secure-route.yaml
  - externalsecrets
  - hive-metastores
  - configs
generatorOptions:
  disableNameSuffixHash: true
