apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-odh-monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'github-receiver-issues'
    receivers:
    - name: 'github-receiver-issues'
      webhook_configs:
        - url: 'http://github-receiver-service.opf-alertreceiver.svc.cluster.local:9393/v1/receiver'
