---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-monitoring
resources:
  - kfdef.yaml
  - alertmanager.yaml
  - alertmanager-service.yaml
  - alertmanager-route.yaml
  - alertmanager-config.yaml
  - ./thanos-query
