apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - ci-prow.yaml
  - ci-prow-test-pods.yaml
  - grafana.yaml
  - jh-idle-culler.yaml
  - prod-aicoe-ci.yaml
  - slack-first.yaml
  - triage-party.yaml
