apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - ci-prow.yaml
  - ci-prow-test-pods.yaml
  - cloudbeaver.yaml
  - cloudbeaver-stage.yaml
  - cluster-logging.yaml
  - curator-operator.yaml
  - grafana.yaml
  - grafana-public.yaml
  - jh-idle-culler.yaml
  - k8s-annotations-exporter.yaml
  - kfp-tekton.yaml
  - meteor-shower.yaml
  - meteor-operator-pipelines.yaml
  - meteor-operator-pushgateway.yaml
  - peribolos-as-a-service.yaml
  - observatorium.yaml
  - opf-kafka.yaml
  - opf-vault.yaml
  - prod-aicoe-ci.yaml
  - reloader.yaml
  - robozome.yaml
  - service-catalog.yaml
  - slack-first.yaml
  - tekton-chains.yaml
  - triage-party.yaml
