apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/project-admin-rolebindings/ray
- ../../../../components/project-logs-reader
- ../../../../components/monitoring-rbac
- ../../../../components/odh-dashboard
kind: Kustomization
namespace: opf-jupyterhub
resources:
- namespace.yaml
