apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- balrog.yaml
- curator.yaml
- local-cluster.yaml
- ocp-prod.yaml
- ocp-staging.yaml
- osc-cl1.yaml
- osc-cl2.yaml
- rick.yaml
- smaug.yaml
- morty.yaml
