apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - cloudbeaver.yaml
  - cluster-resources.yaml
  - das.yaml
  - dex.yaml
  - k8s-annotations-exporter.yaml
  - kfdefs.yaml
  - kfp-tekton.yaml
  - odh-operator.yaml
  - pachyderm.yaml
  - reloader.yaml
