apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - cloudbeaver.yaml
  - cluster-resources.yaml
  - das.yaml
  - dex.yaml
  - kfdefs.yaml
  - odh-operator.yaml
