apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - clusterrolebindings/cluster-readers.yaml
  - oauths/cluster-patch.yaml
  - configmaps/cluster-monitoring-config.yaml
  - configmaps/user-workload-monitoring-config.yaml
  - groups/cluster-admins.yaml
  - groups/cluster-readers.yaml
  - groups/grafana-admin.yaml
  - groups/grafana-editor.yaml
  - groups/grafana-viewer.yaml
  - groups/inception-admins.yaml
  - groups/kafka-admins.yaml
  - groups/kepler-admins.yaml
  - groups/kubeflow-admin.yaml
  - groups/odh-admin.yaml
  - groups/odh-users.yaml
  - groups/openshift-operators-admin.yaml
  - groups/openshift-operators-view.yaml
  - groups/pachyderm-admins.yaml
  - groups/seldon-admin.yaml
  - operators.coreos.com/patches/nfd-sub-patch.yaml
resources:
- ../../../../base/core/configmaps/cluster-monitoring-config
- ../../../../base/core/configmaps/user-workload-monitoring-config
- ../../../../base/core/namespaces/acme-operator
- ../../../../base/core/namespaces/dex
- ../../../../base/core/namespaces/dex-secondary
- ../../../../base/core/namespaces/inception
- ../../../../base/core/namespaces/kafka
- ../../../../base/core/namespaces/kubeflow
- ../../../../base/core/namespaces/markets-svc-dev
- ../../../../base/core/namespaces/odh-jupyterhub
- ../../../../base/core/namespaces/odh-seldon
- ../../../../base/core/namespaces/odh-superset
- ../../../../base/core/namespaces/odh-trino
- ../../../../base/core/namespaces/openmetadata
- ../../../../base/core/namespaces/openshift-nfd
- ../../../../base/core/namespaces/openshift-operators
- ../../../../base/core/namespaces/opf-monitoring
- ../../../../base/core/namespaces/nvidia-gpu-operator
- ../../../../base/core/namespaces/sostrades
- ../../../../base/core/namespaces/aicos-osc-demo
- ../../../../base/operators.coreos.com/operatorgroups/openshift-nfd
- ../../../../base/operators.coreos.com/subscriptions/nfd
- ../../../../base/operators.coreos.com/subscriptions/strimzi-global-operator
- ../../../../base/config.openshift.io/oauths/cluster
- ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
- ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-rb
- ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-reader-k8s-annotations-exporter
- ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-readers
- ../../../../base/user.openshift.io/groups/grafana-admin
- ../../../../base/user.openshift.io/groups/grafana-editor
- ../../../../base/user.openshift.io/groups/grafana-viewer
- ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
- ../../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
- ../../../../base/rbac.authorization.k8s.io/clusterroles/pytorchjobs-create-aggregate-to-admin
- ../../../../base/rbac.authorization.k8s.io/clusterroles/strimzi-aggregate-to-admin
- ../../../../base/user.openshift.io/groups/cluster-admins
- ../../../../base/user.openshift.io/groups/cluster-readers
- ../../../../base/user.openshift.io/groups/inception-admins
- ../../../../base/user.openshift.io/groups/kafka-admins
- ../../../../base/user.openshift.io/groups/kepler-admins
- ../../../../base/user.openshift.io/groups/kubeflow-admin
- ../../../../base/user.openshift.io/groups/odh-admin
- ../../../../base/user.openshift.io/groups/odh-users
- ../../../../base/user.openshift.io/groups/openshift-operators-admin
- ../../../../base/user.openshift.io/groups/openshift-operators-view
- ../../../../base/user.openshift.io/groups/pachyderm-admins
- ../../../../base/user.openshift.io/groups/seldon-admin
- ../../../../base/user.openshift.io/groups/sostrades
- ../../../../base/user.openshift.io/groups/aicos-osc-admins
- ../../../../bundles/external-secrets-operator
- ../../../../bundles/kepler
- ../../../../bundles/grafana-operator
- ../../../../bundles/kfp-tekton
- ../../../../bundles/opendatahub-operator-manual
- ../../../../bundles/openshift-pipelines
- ../../../../bundles/pachyderm-operator
- ../../../../bundles/reloader
- ../../../../bundles/service-catalog-k8s-plugin
- apiserver
- configmaps/service-catalog-k8s-plugin.yaml
- externalsecrets
- ingresscontroller
- machinesets
- nodefeaturediscovery
- operators.coreos.com/operatorgroups/nvidia-gpu-operator
- operators.coreos.com/subscriptions/nvidia-gpu-operator
- machineconfiguration.openshift.io/machineconfigs/kepler
- machineconfiguration.openshift.io/machineconfigs/trino
- machineconfiguration.openshift.io/containerruntimeconfigs/trino
- machineconfiguration.openshift.io/machineconfigpools
- nvidia-gpu
- secret-mgmt
