---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-superset

resources:
  - ../../../../base/superset
  - secure-route.yaml
  - secrets

patchesJson6902:
  - patch: |
      - op: add
        path: /spec/applications/-
        value:
          kustomizeConfig:
            parameters:
              - name: SUPERSET_IMAGE
                value: quay.io/opendatahub/superset:1.1.0
              - name: SUPERSET_MEMORY_REQUESTS
                value: "6Gi"
              - name: SUPERSET_MEMORY_LIMITS
                value: "8Gi"
            repoRef:
              name: opf
              path: odh-manifests/smaug/superset
          name: superset
      - op: add
        path: /spec/repos/-
        value:
          name: opf
          uri: https://github.com/operate-first/apps/tarball/master
    target:
      group: kfdef.apps.kubeflow.org
      kind: KfDef
      name: opendatahub
      version: v1
