---
apiVersion: v1
kind: Secret
metadata:
  name: hue-mysql-secret
  annotations:
    template.openshift.io/expose-username: "{.data['database-user']}"
    template.openshift.io/expose-password: "{.data['database-password']}"
    template.openshift.io/expose-database_name: "{.data['database-name']}"
    template.openshift.io/expose-root_password: |
      {.data['database-root-password']}
stringData:
  database-user: datacatalog
  database-password: datacatalog
  database-name: datacatalog
  database-root-password: root
