---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: trino-catalog
    files:
      - jmx.properties
      - catalogs/operate_first_general.properties
  - name: trino-configfiles
    files:
      - config-coordinator.properties
      - config-worker.properties
      - jvm-coordinator.config
      - jvm-worker.config
      - log.properties
      - node.properties
      - password-authenticator.properties
      - password.db
