---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    deployment: dex
spec:
  selector:
    matchLabels:
      deployment: dex
  template:
    metadata:
      labels:
        deployment: dex
    spec:
      containers:
        - command:
            - "/usr/local/bin/dex"
            - "serve"
            - "/etc/dex/cfg/config.yaml"
          image: ghcr.io/dexidp/dex:v2.35.1
          imagePullPolicy: Always
          name: dex
          ports:
            - containerPort: 5556
            - containerPort: 5557
            - containerPort: 5558
          volumeMounts:
            - mountPath: /etc/dex/cfg
              name: config
            - name: ssl
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
            - name: ssl
              mountPath: /etc/ssl/certs/namespace
              subPath: namespace
            - name: ssl
              mountPath: /etc/ssl/certs/service-ca.crt
              subPath: service-ca.crt
            - name: ssl
              mountPath: /etc/ssl/certs/token
              subPath: token
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: dex-clients
          env:
            - name: OPENSHIFT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dex-sa
                  key: token
      volumes:
        - name: config
          configMap:
            name: dex
        - name: ssl
          secret:
            secretName: dex-sa
            items:
              - key: ca.crt
                path: ca.crt
              - key: namespace
                path: namespace
              - key: service-ca.crt
                path: service-ca.crt
              - key: token
                path: token
