---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opf-seldon

resources:
- namespace.yaml

components:
- ../../../../components/project-admin-rolebindings/data-science
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/project-admin-rolebindings/odh-admin
