---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/cert-manager.io/issuers/ingress-letsencrypt-staging
  - ../../base/core/namespaces/observatorium-operator
  - ../../base/core/namespaces/opf-argo
  - ../../base/core/namespaces/opf-dashboard
  - ../../base/core/namespaces/opf-datacatalog
  - ../../base/core/namespaces/opf-jupyterhub
  - ../../base/core/namespaces/opf-kafka
  - ../../base/core/namespaces/opf-monitoring
  - ../../base/core/namespaces/opf-observatorium
  - ../../base/core/namespaces/opf-superset
  - ../../base/user.openshift.io/groups/argocd-admins
  - ../../base/user.openshift.io/groups/cluster-admins
  - ../../base/user.openshift.io/groups/operate-first

patchesJson6902:
  - path: group-user_patch.yaml
    target:
      group: user.openshift.io
      kind: Group
      name: argocd-admins
      version: v1
  - path: group-user_patch.yaml
    target:
      group: user.openshift.io
      kind: Group
      name: cluster-admins
      version: v1
  - path: group-user_patch.yaml
    target:
      group: user.openshift.io
      kind: Group
      name: operate-first
      version: v1
