---
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  logging: 2
  replicas: 1
  rolloutStrategy: Recreate
  managementState: Managed
  storage:
    pvc:
      claim: image-registry-storage
