apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/project-admin-rolebindings/data-science
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/x-small
kind: Kustomization
namespace: ds-black-flake
resources:
- namespace.yaml
