apiVersion: integreatly.org/v1
kind: GrafanaDataSource
metadata:
  name: datasource
spec:
  name: prometheus-grafanadatasource.yaml
  datasources:
    - name: Prometheus
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
