---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false

    discovery.uri=http://localhost:8080

    web-ui.authentication.type=oauth2
    http-server.authentication.type=PASSWORD,oauth2
    http-server.process-forwarded=true
    http-server.http.port=8080
    http-server.authentication.oauth2.issuer=http://dex-dex.apps.odh-cl1.apps.os-climate.org
    http-server.authentication.oauth2.auth-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/auth
    http-server.authentication.oauth2.token-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/token
    http-server.authentication.oauth2.jwks-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/keys
    http-server.authentication.oauth2.userinfo-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/userinfo
    http-server.authentication.oauth2.client-id=trino
    http-server.authentication.oauth2.client-secret=${ENV:TRINO_OAUTH_SECRET}
    http-server.authentication.oauth2.scopes=openid,groups,email
    http-server.authentication.oauth2.principal-field=email
    http-server.authentication.oauth2.additional-audiences=das
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  log.properties: |-
    io.trino=INFO
  node.properties: |-
    node.environment=$(trino_environment)
    node.data-dir=/tmp/data/trino
  password-authenticator.properties: |-
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
  password.db: |-
    admin:$2y$10$WDwsrDy1Uwa7giTJrRAo1O5MoRjbWi8zT6ugCkibA8KSS5Dx7TQS.
    erik:$2y$10$Mt86mngLFB2nigY/GlMHI.iWQPPk5ieKf5WbkX4BeebBJhNQn01U6
    hukhan:$2y$10$JW7F4BPVPh2J8GS5N9z5t.lmgaQKylrcZt9T3NSPRCzT8kiyrHCii
    mikhail:$2y$10$kk/XazcoKmZGRvUwiM6kgex5QUEOTnVCmk5mU290gXTkArmEdAvLC
    ricardo:$2y$10$aLK8b1tH0bvXGk8GjU2EteokQQ4xH3e29PgyUTtiVsDUmCV2nHVpO
    vincent:$2y$10$93Lnt4vXk1sbhftl3fVE8euqyaCHPWmUrEdP99SRmrXK/XJ6UToDG
  group-provider.properties: |-
    group-provider.name=file
    file.group-file=/etc/trino/group-mapping.properties
  group-mapping.properties: |-
    admins:admin,erikerlandson,caldeirav,HumairAK,MichaelTiemannOSC
    aicoe_osc_demo:oindrillac,aakankshaduggal,shreyanand,michaelclifford,chauhankaranraj,sankbad,harshad16,durandom,erikerlandson
    corporate_data:ludans,caldeirav,DavWinkel,rmorais1,andraNew,ChristianMeyndt,ttschmucker,toki8,LeaADeleris,JeremyGohBNP,amirqamar
    corporate_data_pipeline_developers:ludans,caldeirav,rmorais1,mriefer,idemir-ids,ChristianMeyndt,JeremyGohBNP
    corporate_data_pipeline_admin:ChristianMeyndt
    itr:joriscram,alexanu,caldeirav,DavWinkel,ChristianMeyndt,hbaltzell,ttschmucker,toki8,LeylaJavadova,christian-schellnegger,roland-mf,franz-mf,EWinter21
    itr_pipeline_developers:DavWinkel,alexanu
    itr_pipeline_admin:DavWinkel,alexanu
    physical_risk:NikolaosDimakis,MichaelTiemannOSC,joemoorhouse,mariestephanieprevot,dbferri
    physical_risk_pipeline_developers:joemoorhouse,Floflow,MichaelTiemannOSC,NikolaosDimakis,mariestephanieprevot,floriangallo,dbferri,aliebadi2
    physical_risk_pipeline_admin:MichaelTiemannOSC
    entity_matching:DavWinkel,ludans
    entity_matching_pipeline_developers:DavWinkel,ludans
    entity_matching_pipeline_admin:DavWinkel,ludans
    demo_dv_dev:os-climate-user1
    demo_dv_quant:os-climate-user2
    demo_dv_user:os-climate-user3
  access-control.properties: |-
    access-control.name=file
    security.config-file=/etc/trino/rules.json
  rules.json: |-
    {
      "catalogs": [
      {
        "group": "admins",
        "allow": "all"
      },
      {
        "group": "aicoe_osc_demo|corporate_data.*|itr.*|physical_risk.*",
        "catalog": "osc_datacommons_dev",
        "allow": "all"
      },
      {
        "group": "demo_.*",
        "catalog": "osc_datacommons_dev",
        "allow": "all"
      },
      {
        "allow": "none"
      }
      ],
      "schemas": [
      {
        "group": "admins",
        "owner": true
      },
      {
        "group": "corporate_data.*",
        "catalog": "osc_datacommons_dev",
        "schema": "corporate_data",
        "owner": true
      },
      {
        "group": "itr.*",
        "catalog": "osc_datacommons_dev",
        "schema": "itr",
        "owner": true
      },
      {
        "group": "physical_risk.*",
        "catalog": "osc_datacommons_dev",
        "schema": "physical_risk",
        "owner": true
      },
      {
        "group": "entity_matching.*",
        "catalog": "osc_datacommons_dev",
        "schema": "gleif",
        "owner": true
      },
      {
        "group": "aicoe_osc_demo",
        "catalog": "osc_datacommons_dev",
        "schema": "aicoe_osc_demo|urgentem",
        "owner": true
      },
      {
        "catalog": "osc_datacommons_dev",
        "schema": "demo|sandbox",
        "owner": true
      },
      {
        "owner": false
      }
      ],
      "tables": [
      {
        "group": "admins",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "demo_dv_user|demo_dv_quant",
        "catalog": "osc_datacommons_dev",
        "schema": "demo",
        "table": "demo_dv_backend",
        "privileges": []
      },
      {
        "group": "demo_dv_user|demo_dv_quant",
        "catalog": "osc_datacommons_dev",
        "schema": "demo",
        "table": "demo_dv_userfacing",
        "privileges": ["SELECT"],
        "columns": [
          { "name": "dev1", "allow": false }
        ]
      },
      {
        "group": "demo_dv_user",
        "catalog": "osc_datacommons_dev",
        "schema": "demo",
        "table": "demo_dv_userfacing",
        "privileges": ["SELECT"],
        "columns": [
          { "name": "quant1", "allow": false }
        ]
      },
      {
        "catalog": "osc_datacommons_dev",
        "schema": "demo|sandbox",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "demo_.*",
        "privileges": []
      },
      {
        "group": "corporate_data_pipeline_.*",
        "catalog": "osc_datacommons_dev",
        "schema": "corporate_data",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "itr_pipeline_.*",
        "catalog": "osc_datacommons_dev",
        "schema": "itr",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "physical_risk_pipeline_.*",
        "catalog": "osc_datacommons_dev",
        "schema": "physical_risk",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "entity_matching_pipeline_.*",
        "catalog": "osc_datacommons_dev",
        "schema": "gleif",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "aicoe_osc_demo",
        "catalog": "osc_datacommons_dev",
        "schema": "urgentem|aicoe_osc_demo",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "catalog": "osc_datacommons_dev",
        "privileges": ["SELECT"]
      },
      {
        "privileges": []
      }
      ]
    }
