---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false

    discovery.uri=http://localhost:8080

    web-ui.authentication.type=oauth2
    http-server.authentication.type=PASSWORD,oauth2
    http-server.process-forwarded=true
    http-server.http.port=8080
    http-server.authentication.oauth2.issuer=http://dex-dex.apps.odh-cl1.apps.os-climate.org
    http-server.authentication.oauth2.auth-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/auth
    http-server.authentication.oauth2.token-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/token
    http-server.authentication.oauth2.jwks-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/keys
    http-server.authentication.oauth2.userinfo-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/userinfo
    http-server.authentication.oauth2.client-id=trino
    http-server.authentication.oauth2.client-secret=${ENV:TRINO_OAUTH_SECRET}
    http-server.authentication.oauth2.scopes=openid,groups,email
    http-server.authentication.oauth2.principal-field=email
    http-server.authentication.oauth2.additional-audiences=das
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  log.properties: |-
    io.trino=INFO
  node.properties: |-
    node.environment=$(trino_environment)
    node.data-dir=/tmp/data/trino
  password-authenticator.properties: |-
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
  password.db: |-
    admin:$2y$10$WDwsrDy1Uwa7giTJrRAo1O5MoRjbWi8zT6ugCkibA8KSS5Dx7TQS.
    erik:$2y$10$Mt86mngLFB2nigY/GlMHI.iWQPPk5ieKf5WbkX4BeebBJhNQn01U6
    hukhan:$2y$10$JW7F4BPVPh2J8GS5N9z5t.lmgaQKylrcZt9T3NSPRCzT8kiyrHCii
    mikhail:$2y$10$kk/XazcoKmZGRvUwiM6kgex5QUEOTnVCmk5mU290gXTkArmEdAvLC
    ricardo:$2y$10$aLK8b1tH0bvXGk8GjU2EteokQQ4xH3e29PgyUTtiVsDUmCV2nHVpO
    vincent:$2y$10$93Lnt4vXk1sbhftl3fVE8euqyaCHPWmUrEdP99SRmrXK/XJ6UToDG
    oindrillac:$2y$10$kk1Q4Ls03PxXersv5V/Ew.DjccTBx5QzNIPGBrS3F0aJUHLHVnJkC
    aakankshaduggal:$2y$10$7r00EoU.aiZWg.ZHOQarSusVM9nGEdqq.jjdeX0ATw2i5MWN2SPSe
    shreyanand:$2y$10$/YeIADI8wv31rym/S/yTfOrH3Au2A7A9zgM0Q5JNSqXQ8y1IRF3di
    michaelclifford:$2y$10$/LaXqAuUWoc7PyXyHz1...jV5cNJ5DvSuTGLvYo6FEctmbyYLomi.
    chauhankaranraj:$2y$10$S4i3gvYGeX3YHAgD3AO3d.FHxa9vOY8PyS86O5zN0CdBW6/x7OVv2
    sankbad:$2y$10$yFqgZoaVSSca94pXZql6ue1LbKdfPz0u0Ye9zweU/4DC6ldiqOfIS
    isabelizimm:$2y$10$0FyAEaXQiMSOScG7AeJMaOjgSER3NqPcVxhG8YjfwvEMtIx415KhK
    harshad16:$2y$10$EesX21D8mDR8taJDf.4KrOIp91WSfqe0ZRuU8gxvcOYE3aVPVaqL2
    durandom:$2y$10$PR8Fh0.rH3N2pka/yg2bqelqWUzchjVLaX6Wgyd.FcUlMmU8ZDXB6
    erikerlandson:$2y$10$MbsyvrFh5Trfjk1bVnplKeVzIKollUrKNYJMDZbRXlb05W/UrVQle
    ludans:$2y$10$rpZqi6LmO4rdk/A5jmOpQO90UW1fYahIJLUdUdmSyetayzISbje6m
    caldeirav:$2y$10$IUWQcTQktuCw3dgOX.bRbuAoRbgNSG83.1Wcs6pNBxMxZHPtQ5kf2
    DavWinkel:$2y$10$IAJ8qhSMc43FQ0JZjzmifel7pvPTCP0KiCjJw1v6F.iINKDKsAgxK
    rmorais1:$2y$10$rgAZD0wy57YVf/QWKG.n9OZ83hJWmv0X9xFKvMTyDVrHTAkURqe0m
    andraNew:$2y$10$RItbALxc413zx5p7CG32jOTPRcLSqrD7QOGTAMzmZyVZC.kdrnuBa
    ChristianMeyndt:$2y$10$OMBcZLhySMGhUBSsmWtzx.oT8evygkvrMjCH76q5NiabeOtKBYlV6
    ttschmucker:$2y$10$mMEMRKzJ5sfB.RzreWxmcuTLezLG3WWHkqXIMS5y.2sQkims9TZrm
    toki8:$2y$10$BWWlcU1/G/GxQ8iDDm0qUunO0mjoJvy/bauMZffsXMNQE9qySNGPO
    LeaADeleris:$2y$10$LOldV7LHWidmwRyz9e.EPuuGgafex35iZSR1IIRoSo8CfQ.WG2wcO
    JeremyGohBNP:$2y$10$WwP3cILJ.zVIXRnk1NeDee6fz7sagb/SwNwfGq8JPiGvzDgt461wm
    amirqamar:$2y$10$fDaxttz.y3VBOW8zOtKROecf9bDUa9DCYYMKtyINortQfS.2gIRgK
    joriscram:$2y$10$uf8O4z6Jdfpk5EQ7oAyEJ.3rcV5vT7iJmeNQZ/6OfgrjSe1XiJQOm
    alexanu:$2y$10$SZW472b78i68JDB97fqgWOQ4o9.xLtXqu59Hhe5yv5IM3hS.FREs2
    hbaltzell:$2y$10$/t/k9aG39B0LCiA8ONI5mutKPvjNVmvZG9MLli32LHOxbP4DyLoLS
    LeylaJavadova:$2y$10$QYaaMtycy6qwFm/hgjchEeKiVSTcBduvJyuTWCsNm775eAOnzAw7e
    christian-schellnegger:$2y$10$z8f5FUsgAklvhVfiw320Ge/tnJdOVddPYhrkpkydue3iJp/joykLi
    roland-mf:$2y$10$aURf0czAuWzVo8EHWmsTD.9u.I7gYcyPBZ74obQQHLgmYdCIcqeVW
    franz-mf:$2y$10$VLhCo8gRJMIIoZr.WGf09.X6vzaa4Y/dn6zWbPpVUifswzi2480nC
    EWinter21:$2y$10$LCHzLJCIqZL2X4genVuQVO7crLtaL9btNlqUNttls058PRUnO7GOG
    MichaelTiemannOSC:$2y$10$xRzsTjBgwG2Rf5zIwFlBHefHBlmk80MP0DDFeZrepp7Gt/zTLQS3u

  group-provider.properties: |-
    group-provider.name=file
    file.group-file=/etc/trino/group-mapping.properties
  group-mapping.properties: |-
    admins:admin,erik,hukhan,mikhail,ricardo,vincent,erikerlandson,caldeirav,HumairAK
    aicoe_osc_demo:oindrillac,aakankshaduggal,shreyanand,michaelclifford,chauhankaranraj,sankbad,isabelizimm,harshad16,durandom,erikerlandson
    os_climate_corporate_data_project:ludans,caldeirav,DavWinkel,rmorais1,andraNew,ChristianMeyndt,ttschmucker,toki8,LeaADeleris,JeremyGohBNP,amirqamar
    climate_itr_tool_project:joriscram,alexanu,caldeirav,DavWinkel,ChristianMeyndt,hbaltzell,ttschmucker,toki8,LeylaJavadova,christian-schellnegger,roland-mf,franz-mf,EWinter21
    data_commons_project:erik,caldeirav,MichaelTiemannOSC,hukhan,erikerlandson
  access-control.properties: |-
    access-control.name=file
    security.config-file=/etc/trino/rules.json
  rules.json: |-
    {
      "catalogs": [
      {
        "group": "admins|aicoe_osc_demo|data_commons_project",
        "allow": "all"
      },
      {
        "group": "os_climate_corporate_data_project|climate_itr_tool_project",
        "allow": "read-only"
      },
      {
        "allow": "none"
      }
      ],
      "schemas": [
      {
        "group": "admins",
        "owner": true
      },
      {
        "owner": false
      }
      ],
      "tables": [
      {
        "group": "admins",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "aicoe_osc_demo|data_commons_project",
        "catalog": "OSC_DataCommons_Dev",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "privileges": []
      }
      ]
    }
