apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- airflow-mysql-secrets.yaml
- airflow-secrets.yaml
- mysql.yaml
- mysql-init-scripts.yaml
- mysql-secrets.yaml
- openmetadata-dependencies-config-envs.yaml
- openmetadata-envs.yaml
