---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-smaug-app-logs.yaml
  - thoth-station-datasource.yaml
  - opf-observatorium-thanos-datasource.yaml

generators:
  - secrets-generator.yaml
