apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/
namespace: opf-jupyterhub-idle-culler
commonLabels:
  app: jupyterhub-idle-culler
generators:
  - secrets/secret-generator.yaml
patchesStrategicMerge:
  - deploymentconfig_patch.yaml