---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-route.yaml
  - loki-distributor.yaml
  - loki-query-frontend-oauth-proxy.yaml
  - thanos-query-frontend-oauth-proxy.yaml
  - thanos-receive-oauth-proxy.yaml
