apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management-observability
resources:
- namespace.yaml
components:
- ../../../../components/project-admin-rolebindings/operate-first
