apiVersion: kustomize.config.k8s.io/v1beta1
components:
    - ../../../../components/project-admin-rolebindings/okd-team
kind: Kustomization
namespace: okd-team
resources:
    - namespace.yaml
    - limits.yaml
    - resourcequota.yaml
