---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-jupyterhub
resources:
  - audio-decoder-demo.yaml
  - categorical-encoding.yaml
  - ceph-drive-failure.yaml
  - cloud-price-analysis.yaml
  - configuration-files-analysis.yaml
  - experimental-elyra-notebook-imagestream.yaml
  - hitchhikers-guide.yaml
  - jupyterbook-test.yaml
  - mailing-list-analysis-toolkit.yaml
  - ml-prague-workshop.yaml
  - ocp-ci-analysis.yaml
  - openshift-anomaly-detection.yaml
  - pet-image-detection.yaml
  - ray-ml-notebook.yaml
  - s2i-spark3.0.1-minimal-notebook.yaml
  - time-series.yaml
  - s2i-pytorch-py38-notebook.yaml
  - bu-cs-jupyterbook.yaml
  - ucsls.yaml
  - ope.yaml
  - operate-first-jupyterhub-analysis.yaml
  - htm-applications.yaml
