apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-jupyterhub
resources:
  - audio-decoder-demo.yaml
  - categorical-encoding.yaml
  - ceph-drive-failure.yaml
  - cloud-price-analysis.yaml
  - configuration-files-analysis.yaml
  - experimental-elyra-notebook-imagestream.yaml
  - jupyterbook-test.yaml
  - mailing-list-analysis-toolkit.yaml
  - ml-prague-workshop.yaml
  - ocp-ci-analysis.yaml
  - openshift-anomaly-detection.yaml
  - pet-image-detection.yaml
  - ray-ml-notebook.yaml
  - time-series.yaml
