apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/project-admin-rolebindings/odh-admin
- ../../../../components/project-view-rolebindings/data-science
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
kind: Kustomization
namespace: opf-monitoring
resources:
- namespace.yaml
- resourcequota.yaml
