apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  strimzi.io/cluster: odh-message-bus
resources:
- audio-decoder-decoded-speech.yaml
- audio-decoder-sentiment-text.yaml
- thoth-advise-justification.yaml
- thoth-adviser-re-run.yaml
- thoth-adviser-trigger.yaml
- thoth-hash-mismatch.yaml
- thoth-kebechet-trigger.yaml
- thoth-missing-package-version.yaml
- thoth-missing-package.yaml
- thoth-package-extract-trigger.yaml
- thoth-package-released.yaml
- thoth-provenance-checker-trigger.yaml
- thoth-qebhwt-trigger.yaml
- thoth-si-unanalyzed-package.yaml
- thoth-solved-package.yaml
- thoth-unresolved-package.yaml
- thoth-unrevsolved-package.yaml
- thoth-update-provides-source-distro.yaml
- zero-cluster-app-logs.yaml
