apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
nameSuffix: -smaug
resources:
- apicurio
- b4mad
- chris
- cluster-management
- data-science
- fybrik
- okd-team
- operate-first
- thoth
- workshops
