apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alert-manager.yaml
- image-registry-private-configuration-user.yaml
- pull-secret.yaml
- rook-ceph-external-cluster-details.yaml
- service-catalog-k8s-plugin-tokens.yaml
