apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- ../../cluster-resources
- applications
- projects
configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - configs/argo_cm/dex.config
  - configs/argo_cm/configManagementPlugins
  envs:
    - configs/argo_cm/envs
- name: argocd-rbac-cm
  behavior: replace
  files:
  - configs/argo_rbac_cm/policy.csv
generatorOptions:
  disableNameSuffixHash: true
generators:
- secrets/gpg/secret-generator.yaml
- secrets/auth/secret-generator.yaml
patchesStrategicMerge:
- serviceaccounts/argocd-dex-server.yaml
