apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github-client-secret.yaml
- multiclusterhub-operator-pull-secret.yaml
- pull-secret.yaml
- rook-ceph-external-cluster-details.yaml
- thanos-object-storage.yaml
