---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/groups/argocd-admins
  - ../../base/groups/data-science
  - ../../base/groups/mesh-for-data
  - ../../base/groups/open-aiops
  - ../../base/groups/operate-first
  - ../../base/groups/rekor
  - ../../base/groups/thoth
  - ../../base/groups/workshops

generators:
  - secret-generator.yaml
