---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common

  - ../../../base/apiextensions.k8s.io/customresourcedefinitions/gitbasedconfigs.sdap.apache.org
  - ../../../base/apiextensions.k8s.io/customresourcedefinitions/kfdefs.kfdef.apps.kubeflow.org
  - ../../../base/apiextensions.k8s.io/customresourcedefinitions/observatoria.core.observatorium.io
  - ../../../base/apiextensions.k8s.io/customresourcedefinitions/prowjobs.prow.k8s.io
  - ../../../base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.cluster.ray.io
  - ../../../base/config.openshift.io/oauths/cluster
  - ../../../base/core/namespaces/acme-operator
  - ../../../base/core/namespaces/apicurio-apicurio-registry
  - ../../../base/core/namespaces/as-pushgateway
  - ../../../base/core/namespaces/b4mad-minecraft
  - ../../../base/core/namespaces/cnv-testing
  - ../../../base/core/namespaces/codait-advo
  - ../../../base/core/namespaces/democratic-csi
  - ../../../base/core/namespaces/ds-black-flake
  - ../../../base/core/namespaces/ds-example-project
  - ../../../base/core/namespaces/ds-ml-workflows-ws
  - ../../../base/core/namespaces/fde-audio-decoder-demo
  - ../../../base/core/namespaces/koku-metrics-operator
  - ../../../base/core/namespaces/kubeflow
  - ../../../base/core/namespaces/lab-cicd-1-jump-app-cicd
  - ../../../base/core/namespaces/lab-cicd-1-jump-app-dev
  - ../../../base/core/namespaces/lab-cicd-2-jump-app-cicd
  - ../../../base/core/namespaces/lab-cicd-2-jump-app-dev
  - ../../../base/core/namespaces/lab-cicd-3-jump-app-cicd
  - ../../../base/core/namespaces/lab-cicd-3-jump-app-dev
  - ../../../base/core/namespaces/lab-cicd-4-jump-app-cicd
  - ../../../base/core/namespaces/lab-cicd-4-jump-app-dev
  - ../../../base/core/namespaces/local-storage
  - ../../../base/core/namespaces/m4d-blueprints
  - ../../../base/core/namespaces/m4d-system
  - ../../../base/core/namespaces/mesh-for-data
  - ../../../base/core/namespaces/metallb-system
  - ../../../base/core/namespaces/mwperf-horreum
  - ../../../base/core/namespaces/observatorium-operator
  - ../../../base/core/namespaces/open-aiops
  - ../../../base/core/namespaces/opendatahub-operator
  - ../../../base/core/namespaces/openshift-cnv
  - ../../../base/core/namespaces/openshift-insights
  - ../../../base/core/namespaces/openshift-logging
  - ../../../base/core/namespaces/openshift-metering
  - ../../../base/core/namespaces/openshift-monitoring
  - ../../../base/core/namespaces/openshift-operators
  - ../../../base/core/namespaces/openshift-operators-redhat
  - ../../../base/core/namespaces/openshift-serverless
  - ../../../base/core/namespaces/openshift-storage
  - ../../../base/core/namespaces/opf-alertreceiver
  - ../../../base/core/namespaces/opf-argo
  - ../../../base/core/namespaces/opf-auth
  - ../../../base/core/namespaces/opf-ci-pipelines
  - ../../../base/core/namespaces/opf-ci-prow
  - ../../../base/core/namespaces/opf-ci-test-pods
  - ../../../base/core/namespaces/opf-dashboard
  - ../../../base/core/namespaces/opf-datacatalog
  - ../../../base/core/namespaces/opf-google-spark-operator
  - ../../../base/core/namespaces/opf-jupyterhub
  - ../../../base/core/namespaces/opf-jupyterhub-stage
  - ../../../base/core/namespaces/opf-kafka
  - ../../../base/core/namespaces/opf-monitoring
  - ../../../base/core/namespaces/opf-observatorium
  - ../../../base/core/namespaces/opf-seldon
  - ../../../base/core/namespaces/opf-slack-first
  - ../../../base/core/namespaces/opf-superset
  - ../../../base/core/namespaces/opf-trino
  - ../../../base/core/namespaces/osc-playground
  - ../../../base/core/namespaces/pixel-demos
  - ../../../base/core/namespaces/pixel-vault
  - ../../../base/core/namespaces/pulp-operator
  - ../../../base/core/namespaces/quarkus-extension-registry
  - ../../../base/core/namespaces/ray-odh-integration
  - ../../../base/core/namespaces/redhat-cto-ns
  - ../../../base/core/namespaces/sa-dach-anwendertreffen
  - ../../../base/core/namespaces/sa-dach-openshift-examples
  - ../../../base/core/namespaces/sigstore-deploy
  - ../../../base/core/namespaces/sdap
  - ../../../base/core/namespaces/tekton-pipelines
  - ../../../base/core/namespaces/thoth-amun-api-prod
  - ../../../base/core/namespaces/thoth-amun-inspection-prod
  - ../../../base/core/namespaces/thoth-backend-prod
  - ../../../base/core/namespaces/thoth-bots-prod
  - ../../../base/core/namespaces/thoth-deployment-examples
  - ../../../base/core/namespaces/thoth-frontend-prod
  - ../../../base/core/namespaces/thoth-graph-prod
  - ../../../base/core/namespaces/thoth-infra-prod
  - ../../../base/core/namespaces/thoth-middletier-prod
  - ../../../base/core/namespaces/thoth-pulp-experiments
  - ../../../base/core/namespaces/thoth-test-core
  - ../../../base/core/namespaces/tufts-dcc-6
  - ../../../base/core/namespaces/uky-hpc-workload-generator
  - ../../../base/core/namespaces/ws-ml-prague
  - ../../../base/core/persistentvolumeclaims/image-registry-storage
  - ../../../base/imageregistry.operator.openshift.io/configs/cluster
  - ../../../base/operator.openshift.io/ingresscontrollers/default
  - ../../../base/operators.coreos.com/catalogsources/pulp-catalog
  - ../../../base/operators.coreos.com/operatorgroups/cluster-logging
  - ../../../base/operators.coreos.com/operatorgroups/koku-metrics-operator
  - ../../../base/operators.coreos.com/operatorgroups/local-storage-operator-group
  - ../../../base/operators.coreos.com/operatorgroups/openshift-cnv-rn5jf
  - ../../../base/operators.coreos.com/operatorgroups/openshift-metering
  - ../../../base/operators.coreos.com/operatorgroups/openshift-operators-redhat
  - ../../../base/operators.coreos.com/operatorgroups/openshift-serverless
  - ../../../base/operators.coreos.com/operatorgroups/openshift-storage
  - ../../../base/operators.coreos.com/operatorgroups/pulp-operator
  - ../../../base/operators.coreos.com/subscriptions/cluster-logging
  - ../../../base/operators.coreos.com/subscriptions/elasticsearch-operator
  - ../../../base/operators.coreos.com/subscriptions/koku-metrics-operator
  - ../../../base/operators.coreos.com/subscriptions/kubevirt-hyperconverged
  - ../../../base/operators.coreos.com/subscriptions/local-storage-operator
  - ../../../base/operators.coreos.com/subscriptions/metering-operator
  - ../../../base/operators.coreos.com/subscriptions/ocs-operator
  - ../../../base/operators.coreos.com/subscriptions/openshift-pipelines-operator-rh
  - ../../../base/operators.coreos.com/subscriptions/pulp-operator
  - ../../../base/operators.coreos.com/subscriptions/serverless-operator
  - ../../../base/operators.coreos.com/subscriptions/web-terminal
  - ../../../base/policy/podsecuritypolicies/controller
  - ../../../base/policy/podsecuritypolicies/speaker
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/argocd-manager
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-rb
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-logs-readers
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/metallb-allow-privileged
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/metallb-system:controller
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/metallb-system:speaker
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/metrics
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-controller-rb
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-node-rb
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/observatorium-operator
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/opendatahub-operator
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/opf-cluster-metrics-federation
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/scc-anyuid-observatorium
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/scc-anyuid-tufts-dcc-6
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-tufts-dcc-6
  - ../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
  - ../../../base/rbac.authorization.k8s.io/clusterroles/cluster-logs-reader
  - ../../../base/rbac.authorization.k8s.io/clusterroles/metallb-system:controller
  - ../../../base/rbac.authorization.k8s.io/clusterroles/metallb-system:speaker
  - ../../../base/rbac.authorization.k8s.io/clusterroles/metrics
  - ../../../base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-controller-cr
  - ../../../base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-node-cr
  - ../../../base/rbac.authorization.k8s.io/clusterroles/oauth-token-access-review
  - ../../../base/rbac.authorization.k8s.io/clusterroles/observatorium-operator
  - ../../../base/rbac.authorization.k8s.io/clusterroles/opendatahub-operator
  - ../../../base/rbac.authorization.k8s.io/clusterroles/prow-aggregate-to-admin
  - ../../../base/rbac.authorization.k8s.io/clusterroles/prow-aggregate-to-edit
  - ../../../base/rbac.authorization.k8s.io/clusterroles/prow-aggregate-to-view
  - ../../../base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-admin
  - ../../../base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-edit
  - ../../../base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-view
  - ../../../base/rbac.authorization.k8s.io/clusterroles/ray-aggregate-to-admin
  - ../../../base/security.openshift.io/securitycontextconstraints/uky-hpc-workload-generator-hostpath
  - ../../../base/storage.k8s.io/csidrivers/org.democratic-csi.nfs
  - ../../../base/storage.k8s.io/storageclasses/moc-nfs-csi
  - ../../../base/storage.k8s.io/storageclasses/ocs-storagecluster-cephfs
  - ../../../base/user.openshift.io/groups/cluster-admins

  - clusterversion.yaml
  - nodenetworkconfigurationpolicies/moc-nfs-network.yaml
  - kubeletconfigs/increase-worker-system-reserved-memory.yaml
  - machinehealthchecks/work-healthcheck.yaml

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
  - storageclasses/moc-nfs-csi_patch.yaml
  - subscriptions/cluster-logging-operator_patch.yaml
  - subscriptions/elastic-operator_patch.yaml
  - subscriptions/kubevirt-hyperconverged_patch.yaml
  - subscriptions/local-storage-operator_patch.yaml
  - subscriptions/metering-ocp_patch.yaml
  - subscriptions/ocs-operator_patch.yaml
  - subscriptions/openshift-pipelines-operator-rh_patch.yaml
  - subscriptions/serverless-operator_patch.yaml
  - subscriptions/web-terminal.yaml
