---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aakankshaduggal.yaml
  - antter.yaml
  - bkoz.yaml
  - cdolfi.yaml
  - chauhankaranraj.yaml
  - hemajv.yaml
  - isabelizimm.yaml
  - michaelclifford.yaml
  - oindrillac.yaml
  - pacospace.yaml
  - shreyanand.yaml
