---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: cosigned-v0.1.9
    app.kubernetes.io/name: cosigned
    app.kubernetes.io/instance: cosigned
    app.kubernetes.io/version: "v1.4.1"
    app.kubernetes.io/managed-by: Helm
    control-plane: cosigned-webhook
  name: webhook
  namespace: cosign-system
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: cosigned
    app.kubernetes.io/instance: cosigned
    control-plane: cosigned-webhook