apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
components:
    - ../../../../components/project-admin-public
    - ../../../../components/project-admin-rolebindings/operate-first
    - ../../../../components/limitranges/default
namespace: elyra-aidevsecops-tutorial
