apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  strimzi.io/cluster: odh-message-bus
resources:
- audio-decoder.yaml
- cluster-logging.yaml
- opf-public-demo.yaml
- thoth.yaml
- emea-sa-od-demo.yaml
- ddas.yaml
- smartvillage.yaml
