---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-jupyterhub
resources:
  - categorical-encoding.yaml
  - ocp-ci-analysis.yaml
  - ceph-drive-failure.yaml
  - configuration-files-analysis.yaml
  - cloud-price-analysis.yaml
