---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../moc-base
  - ../../base/clusterroles/prow-aggregate-to-admin
  - ../../base/clusterroles/prow-aggregate-to-edit
  - ../../base/clusterroles/prow-aggregate-to-view
  - ../../base/clusterroles/cluster-logs-reader
  - ../../base/clusterroles/metrics
  - ../../base/clusterroles/observatorium-operator
  - ../../base/clusterrolebindings/argocd-manager
  - ../../base/clusterrolebindings/cluster-admins-rb
  - ../../base/clusterrolebindings/cluster-logs-readers
  - ../../base/clusterrolebindings/cluster-metrics-federation
  - ../../base/clusterrolebindings/metrics
  - ../../base/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci
  - ../../base/crds/prow.k8s.io
  - ../../base/crds/observatorium.io
  - ../../base/groups/cluster-admins
  - ../../base/imageregistryconfigs/cluster
  - ../../base/ingresscontrollers/default
  - ../../base/namespaces/argocd
  - ../../base/namespaces/cert-manager
  - ../../base/namespaces/ds-black-flake
  - ../../base/namespaces/ds-example-project
  - ../../base/namespaces/istio-system
  - ../../base/namespaces/knative-serving
  - ../../base/namespaces/kube-system
  - ../../base/namespaces/kubeflow
  - ../../base/namespaces/local-storage
  - ../../base/namespaces/m4d-blueprints
  - ../../base/namespaces/m4d-system
  - ../../base/namespaces/mesh-for-data
  - ../../base/namespaces/observatorium-operator
  - ../../base/namespaces/open-aiops
  - ../../base/namespaces/openshift-cnv
  - ../../base/namespaces/openshift-logging
  - ../../base/namespaces/openshift-metering
  - ../../base/namespaces/openshift-monitoring
  - ../../base/namespaces/openshift-operators
  - ../../base/namespaces/openshift-operators-redhat
  - ../../base/namespaces/openshift-storage
  - ../../base/namespaces/opf-argo
  - ../../base/namespaces/opf-auth
  - ../../base/namespaces/opf-ci-pipelines
  - ../../base/namespaces/opf-ci-prow
  - ../../base/namespaces/opf-ci-test-pods
  - ../../base/namespaces/opf-dashboard
  - ../../base/namespaces/opf-datacatalog
  - ../../base/namespaces/opf-jupyterhub
  - ../../base/namespaces/opf-kafka
  - ../../base/namespaces/opf-monitoring
  - ../../base/namespaces/opf-observatorium
  - ../../base/namespaces/opf-superset
  - ../../base/namespaces/tekton-pipelines
  - ../../base/namespaces/thoth-amun-api-prod
  - ../../base/namespaces/thoth-amun-inspection-prod
  - ../../base/namespaces/thoth-backend-prod
  - ../../base/namespaces/thoth-bots-prod
  - ../../base/namespaces/thoth-deployment-examples
  - ../../base/namespaces/thoth-frontend-prod
  - ../../base/namespaces/thoth-graph-prod
  - ../../base/namespaces/thoth-infra-prod
  - ../../base/namespaces/thoth-middletier-prod
  - ../../base/namespaces/ws-ml-prague
  - ../../base/oauths/cluster
  - ../../base/operatorgroups/local-storage
  - ../../base/operatorgroups/openshift-logging
  - ../../base/operatorgroups/openshift-cnv
  - ../../base/operatorgroups/openshift-metering
  - ../../base/operatorgroups/openshift-operators-redhat
  - ../../base/operatorgroups/openshift-storage
  - ../../base/subscriptions/cluster-logging-operator
  - ../../base/subscriptions/elastic-operator
  - ../../base/subscriptions/kubevirt-hyperconverged
  - ../../base/subscriptions/metering-ocp
  - ../../base/subscriptions/ocs-operator
  - ../../base/subscriptions/opendatahub-operator
  - ../../base/subscriptions/openshift-pipelines-operator-rh

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
  - imageregistryconfigs/image-registry-storage_patch.yaml
