apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  strimzi.io/cluster: odh-message-bus
resources:
- audio-decoder-decoded-speech.yaml
- audio-decoder-sentiment-text.yaml
- balrog-cluster-app-logs.yaml
- balrog-cluster-audit-logs.yaml
- balrog-cluster-infra-logs.yaml
- infra-cluster-app-logs.yaml
- infra-cluster-audit-logs.yaml
- infra-cluster-infra-logs.yaml
- rick-cluster-app-logs.yaml
- rick-cluster-audit-logs.yaml
- rick-cluster-infra-logs.yaml
- smaug-cluster-app-logs.yaml
- smaug-cluster-audit-logs.yaml
- smaug-cluster-infra-logs.yaml
- thoth-advise-justification.yaml
- thoth-adviser-trigger.yaml
- thoth-build-analysis-trigger.yaml
- thoth-cve-provided.yaml
- thoth-hash-mismatch.yaml
- thoth-kebechet-run-url.yaml
- thoth-kebechet-trigger.yaml
- thoth-missing-package-version.yaml
- thoth-missing-package.yaml
- thoth-package-extract-trigger.yaml
- thoth-package-released.yaml
- thoth-provenance-checker-trigger.yaml
- thoth-qebhwt-trigger.yaml
- thoth-si-unanalyzed-package.yaml
- thoth-solved-package.yaml
- thoth-unresolved-package.yaml
- thoth-unrevsolved-package.yaml
- thoth-update-provides-source-distro.yaml
