---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/kafka
  - topics

patchesJson6902:
  - patch: |
      - op: add
        path: /spec/applications/-
        value:
          kustomizeConfig:
            repoRef:
              name: opf
              path: odh/overlays/moc/kafka/overrides
          name: superset
      - op: add
        path: /spec/repos/-
        value:
          name: opf
          uri: https://github.com/operate-first/apps/tarball/master
    target:
      group: kfdef.apps.kubeflow.org
      kind: KfDef
      name: opendatahub
      version: v1
