---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter
  labels:
    name: postgres-exporter
    template: dh-data-catalog
    app: thriftserver
stringData:
  DATA_SOURCE_NAME: |
    postgresql://datacatalog:datacatalog@localhost:5432/datacatalog?sslmode=disable
