---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - remote-write-moc-infra.yaml
  - remote-write-moc-smaug.yaml
  - thanos-query-frontend-oauth-proxy.yaml
  - thanos-receive-oauth-proxy.yaml
