kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: manageiq
resources:
    - namespace.yaml
    - resourcequota.yaml
components:
    - ../../../../components/limitranges/default
    - ../../../../components/project-admin-rolebindings/manageiq
