---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - provider-connections
  - klusterletaddonconfigs/alex.yaml
  - klusterletaddonconfigs/curator.yaml
  - klusterletaddonconfigs/devconfus2021.yaml
  - klusterletaddonconfigs/local-cluster.yaml
  - klusterletaddonconfigs/ocp-prod.yaml
  - klusterletaddonconfigs/osc-cl1.yaml
  - klusterletaddonconfigs/rick.yaml
  - klusterletaddonconfigs/smaug.yaml
  - klusterletaddonconfigs/zero.yaml
