---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  prometheus: odh-monitoring
resources:
  - observatorium-servicemonitor.yaml
  - argocd-servicemonitor.yaml
  - apicurio-registry-servicemonitor.yaml
  - meteor-servicemonitor.yaml
